### ISSUE TITLE
Branch set to 3.3 for branch/3.4

### ISSUE THREAD

**Issue by hfiguiere** [flathub/org.godotengine.godot.BaseApp#19]
The `branch` should be set properly or not set at all.

I believe this is why https://github.com/flathub/com.orama_interactive.Pixelorama/pull/12 is failing.

**Comment by Calinou** [comment]
Fixed by https://github.com/flathub/org.godotengine.godot.BaseApp/commit/275da583594b1235cd772681132ba06c0d00f34b.

**Comment by hfiguiere** [comment]
yeah I was waiting for the build to be published to close it.

Also I'll need to retrigger a 3.3 build just to be sure

**Comment by hfiguiere** [comment]
apparently 3.3 is ok

**Comment by hfiguiere** [comment]
```
godot-runner --version
3.3.4.stable.flathub.faf3f883d
```

**Comment by hfiguiere** [comment]
it's out now.
