### ISSUE TITLE
Support for Godot 4

### ISSUE THREAD

**Issue by OverloadedOrama** [flathub/org.godotengine.godot.BaseApp#39]
Is support for Godot 4 planned? [Pixelorama](https://flathub.org/apps/com.orama_interactive.Pixelorama) v1.0 is about to release very soon, and since it's using Godot 4.2, it is going to need the BaseApp to support Godot 4. Since Godot 4.3 is just around the corner, I wouldn't mind if the BaseApp skipped 4.2 and went straight for 4.3, as I'm also planning to use 4.3 for the next Pixelorama version after v1.0.

**Comment by Calinou** [comment]
Yes, but I don't have time to work on it personally, so someone else will have to take on this work.

~~Note that PRs can't create new branches and this repository has protected branch creation, so Flathub admins must create the `branch/4.3` branch IIRC.~~

**Comment by MateusRodCosta** [comment]
I have some skills in shipping Flatpaks but have yet to ship a Godot game or any other type of project that needs a specific "BaseApp". I would like to help here, what would be need to port to Godot 4.3?

**Comment by Calinou** [comment]
> I would like to help here, what would be need to port to Godot 4.3?

This is mostly about updating the buildsystem in the Flatpak manifest to follow the changes that were made in https://github.com/flathub/org.godotengine.Godot between and 4.x. Compare that repository with https://github.com/flathub/org.godotengine.Godot3 which still builds Godot 3.x for reference.

**Comment by MateusRodCosta** [comment]
I tried adapting to Godot 4.3-beta3, here are the results: https://github.com/MateusRodCosta/org.godotengine.godot.BaseApp/tree/branch/4.3

It does build successfully but I didn't test it yet though.

**Comment by MateusRodCosta** [comment]
Godot 4.2 (4.2.2) now supported as https://github.com/MateusRodCosta/org.godotengine.godot.BaseApp/tree/branch/4.2

**Comment by OverloadedOrama** [comment]
> Godot 4.2 (4.2.2) now supported as https://github.com/MateusRodCosta/org.godotengine.godot.BaseApp/tree/branch/4.2

Tested the 4.2 baseapp with Pixelorama 1.0 and it seems to be working well!

**Comment by OverloadedOrama** [comment]
> I tried adapting to Godot 4.3-beta3, here are the results: https://github.com/MateusRodCosta/org.godotengine.godot.BaseApp/tree/branch/4.3

We should merge that branch as well now that 4.3 stable is out.

**Comment by MateusRodCosta** [comment]
> > I tried adapting to Godot 4.3-beta3, here are the results: https://github.com/MateusRodCosta/org.godotengine.godot.BaseApp/tree/branch/4.3
> 
> We should merge that branch as well now that 4.3 stable is out.

I deleted that branch and kinda re-did the 4.2 branch based on 3.5-23.08.
I will re-do the 4.3 branch soon.

**Comment by Calinou** [comment]
Implemented by:

- https://github.com/flathub/org.godotengine.godot.BaseApp/pull/40
- https://github.com/flathub/org.godotengine.godot.BaseApp/pull/41

**Comment by MateusRodCosta** [comment]
@Calinou Seems the 24.08 fdo runtime got released recently. Should we go ahead and create the `4.2-24.08` and `4.3-24.08` branches or should we wait for the Godot editor to use 24.08 first?

**Comment by Calinou** [comment]
> @Calinou Seems the 24.08 fdo runtime got released recently. Should we go ahead and create the `4.2-24.08` and `4.3-24.08` branches or should we wait for the Godot editor to use 24.08 first?

Sorry for the delay in the reply. You can open a PR to update its runtime here and on org.godotengine.Godot :slightly_smiling_face: 

I've created `branch/4.3-24.08` in this repository, which you can use as a base for your PR. I don't think we need to update the runtime for `branch/4.2` as I don't think it'll remain used for very long.

**Comment by MateusRodCosta** [comment]
@Calinou What are your thoughts about 3.5-24.08 and [Godot 3.6](https://godotengine.org/article/godot-3-6-finally-released/)?

**Comment by Calinou** [comment]
> @Calinou What are your thoughts about 3.5-24.08 and [Godot 3.6](https://godotengine.org/article/godot-3-6-finally-released/)?

3.6 was added in https://github.com/flathub/org.godotengine.godot.BaseApp/pull/45.

Regarding `3.5-2408`, I've created a branch for it, so feel free to open a PR for it.

**Comment by OverloadedOrama** [comment]
If we want to update to newer Godot versions, should the new branches be created first, or is it okay to open the PR and an admin can create the branch later? I've [made a commit that updates to Godot 4.4](https://github.com/OverloadedOrama/org.godotengine.godot.BaseApp/commit/3a4153f6df8456cde7f7eee7825d0ce9f2825a11), but I'm unsure if I should create a PR or ask for a branch to be created first.

Should new versions also have multiple branches for the different runtimes, or should they use the latest one only (currently 24.08)?

**Comment by Calinou** [comment]
I've created `branch/4.4` based on `branch/4.3-24.08`. Feel free to open a PR against `branch/4.4` 🙂 

Once the 25.08 runtime comes out in August 2025, I'll create `branch/4.4-25.08`.
